# Generated by Django 4.1.3 on 2022-12-11 12:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_alter_blog_options_alter_blog_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/blogs/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='blogimages',
            name='upload_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата загрузки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogimages',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_photos', to='app_blog.blog', verbose_name='Блог'),
        ),
    ]
