# Generated by Django 4.1.4 on 2022-12-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Название')),
                ('isbn', models.CharField(max_length=200, verbose_name='ISBN')),
                ('year', models.IntegerField(max_length=4, verbose_name='Год выпуска')),
                ('pages', models.IntegerField(verbose_name='Количество страниц')),
            ],
        ),
    ]
