# Generated by Django 4.1.4 on 2022-12-14 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_author', '0001_initial'),
        ('app_books', '0002_alter_book_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'year', 'pages'], 'verbose_name': 'книга', 'verbose_name_plural': 'книги'},
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='app_author.author', verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
    ]
