# Generated by Django 4.1.4 on 2022-12-14 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_author', '0001_initial'),
        ('app_books', '0003_alter_book_options_book_author_alter_book_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_author', to='app_author.author', verbose_name='Автор'),
        ),
    ]
