# Generated by Django 4.1.3 on 2022-12-08 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(max_length=5000, verbose_name='Содержание')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('publicised_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
                ('published', models.BooleanField(default=False, verbose_name='Пройдена модерация')),
                ('tag', models.CharField(max_length=300, verbose_name='Тег для новости')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь из DJDB')),
            ],
            options={
                'db_table': 'news',
                'ordering': ['-publicised_at'],
            },
        ),
    ]
