# Generated by Django 4.1.3 on 2022-12-08 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_news', '0004_newsitem_published_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='published_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_moder_user', to=settings.AUTH_USER_MODEL, verbose_name='Кем опубликована (AbstractUser)'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_user', to=settings.AUTH_USER_MODEL, verbose_name='Чья новость (AbstractUser)'),
        ),
    ]
