# Generated by Django 4.1.3 on 2022-12-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-create_at'], 'verbose_name': 'блог', 'verbose_name_plural': 'блоги'},
        ),
        migrations.AlterModelTable(
            name='blog',
            table='blogs',
        ),
    ]
