# Generated by Django 4.1.3 on 2022-12-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_blogimages_image_blogimages_upload_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogimages',
            options={'ordering': ['blog', '-upload_at'], 'verbose_name': 'фотка блога', 'verbose_name_plural': 'фотки блогов'},
        ),
        migrations.AlterModelTable(
            name='blogimages',
            table='blog_images',
        ),
    ]
