# Generated by Django 4.1.3 on 2022-12-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_alter_blogimages_options_alter_blogimages_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogimages',
            options={'ordering': ['blog', '-upload_at'], 'verbose_name': 'фотка блога', 'verbose_name_plural': 'фотки блога'},
        ),
    ]
