# Generated by Django 4.1.3 on 2022-12-13 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_blog', '0005_alter_blogimages_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-create_at'], 'verbose_name': 'tid_models_blog_meta_vn', 'verbose_name_plural': 'tid_models_blog_meta_vnp'},
        ),
        migrations.AlterModelOptions(
            name='blogimages',
            options={'ordering': ['blog', '-upload_at'], 'verbose_name': 'tid_models_blog_images_meta_vn', 'verbose_name_plural': 'tid_models_blog_images_meta_vnp'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=5000, verbose_name='tid_models_blog_text'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='tid_blog_label_created_at'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='header',
            field=models.CharField(max_length=200, verbose_name='tid_label_header'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='tid_blog_label_updated_at'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to=settings.AUTH_USER_MODEL, verbose_name='tid_models_blog_user'),
        ),
        migrations.AlterField(
            model_name='blogimages',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_photos', to='app_blog.blog', verbose_name='tid_models_blog_meta_vn'),
        ),
        migrations.AlterField(
            model_name='blogimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/blogs/', verbose_name='tid_label_images'),
        ),
        migrations.AlterField(
            model_name='blogimages',
            name='upload_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='tid_models_blog_images_upload_at'),
        ),
    ]
