# Generated by Django 4.1.3 on 2022-12-03 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название статуса')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тип объявления')),
            ],
        ),
        migrations.CreateModel(
            name='PriceCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код валюты')),
                ('title', models.CharField(max_length=100, verbose_name='Название валюты')),
                ('sign', models.CharField(max_length=5, verbose_name='Знак')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название региона')),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1500, verbose_name='Заголовок')),
                ('description', models.CharField(default='', max_length=1000, verbose_name='Описание')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('price_value', models.FloatField(default=0, verbose_name='Цена в у.е.')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('price_currency', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currencier', to='advertisements.pricecurrency', verbose_name='Валюта')),
                ('region', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regioner', to='advertisements.region', verbose_name='Регион')),
                ('status', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuser', to='advertisements.advertisementstatus', verbose_name='Статус')),
                ('typer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typer', to='advertisements.advertisementtype', verbose_name='Тип')),
            ],
            options={
                'db_table': 'advertisements',
                'ordering': ['title'],
            },
        ),
    ]
