# Generated by Django 4.1.3 on 2022-12-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_category_user_advertisement_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisementstatus',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='advertisementtype',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='pricecurrency',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='advertisementstatus',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Доступен для выбора'),
        ),
        migrations.AddField(
            model_name='advertisementstatus',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Сортировка отображения'),
        ),
        migrations.AddField(
            model_name='advertisementtype',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Доступен для выбора'),
        ),
        migrations.AddField(
            model_name='advertisementtype',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Сортировка отображения'),
        ),
        migrations.AddField(
            model_name='pricecurrency',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Доступен для выбора'),
        ),
        migrations.AddField(
            model_name='pricecurrency',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Сортировка отображения'),
        ),
        migrations.AlterModelTable(
            name='advertisementstatus',
            table='advertisement_statuses',
        ),
        migrations.AlterModelTable(
            name='advertisementtype',
            table='advertisement_types',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='pricecurrency',
            table='currencies',
        ),
        migrations.AlterModelTable(
            name='region',
            table='regions',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
