# Generated by Django 4.1.3 on 2022-12-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_alter_advertisementstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='publicised_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата публикации'),
        ),
    ]
