# Generated by Django 4.1.3 on 2022-12-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_alter_category_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='publicised_at',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
    ]
