# Generated by Django 4.1.3 on 2022-12-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsitem',
            options={'ordering': ['-publicised_at']},
        ),
    ]
