# Generated by Django 4.1.3 on 2022-12-04 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsitem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField(verbose_name='IP-адрес')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('news_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newser', to='news.newsitem', verbose_name='Новость')),
            ],
            options={
                'db_table': 'commentaries',
                'ordering': ['-create_at'],
            },
        ),
    ]
