# Generated by Django 4.1.3 on 2022-12-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='news_id',
            new_name='news',
        ),
    ]
