# Generated by Django 4.1.3 on 2022-12-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_comment_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='publicised_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
