# Generated by Django 4.1.3 on 2022-12-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_newsitem_publicised_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default=1, max_length=200, verbose_name='Имя комментатора'),
            preserve_default=False,
        ),
    ]
