# Generated by Django 4.1.3 on 2022-12-06 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ipaddress',
        ),
    ]
