# Generated by Django 4.1.3 on 2022-12-08 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_alter_newsitem_options_alter_newsitem_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsitem',
            options={'ordering': ['-publicised_at'], 'permissions': (('can_publish', 'Может публиковать'),), 'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
    ]
