# Generated by Django 4.1.3 on 2022-12-08 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_news', '0003_alter_newsitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='published_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_moder_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь из DJDB'),
        ),
    ]
