# Generated by Django 4.1.3 on 2022-12-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0005_alter_newsitem_published_by_alter_newsitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='publicised_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
