# Generated by Django 4.1.3 on 2022-12-08 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0006_alter_newsitem_publicised_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsitem',
            options={'ordering': ['-create_at'], 'permissions': (('can_publish', 'Может публиковать'),), 'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
    ]
